CREATE TABLE test (My_Date DATE, My_Time TIME, My_DateTime DATETIME);

SELECT * FROM test;

INSERT INTO test
VALUES (CURRENT_DATE(), CURRENT_TIME(), NOW());

INSERT INTO test
VALUES (CURRENT_DATE() +1, NULL, NULL);    --      +1 To NEXT DATE 

INSERT INTO test
VALUES (CURRENT_DATE() -1, NULL, NULL);    --      -1 To PREVIOUS DATE

INSERT INTO test
VALUES (NULL, CURRENT_TIME(), NULL);

DELETE FROM test
WHERE My_Date IS NULL;

INSERT INTO test
VALUES(NULL,
	   DATE_ADD(CURRENT_TIME(), INTERVAL '2:30' HOUR_MINUTE), --    DATE_ADD() is a function
       NULL);

INSERT INTO test
VALUES (
    NULL,
    NULL,
    DATE_SUB(DATE_ADD(NOW(), INTERVAL 1 DAY), INTERVAL '2:03' HOUR_MINUTE)
);


DROP TABLE test;
