 CREATE TABLE TRANSACTION(
 transaction_id INT PRIMARY KEY AUTO_INCREMENT,
 Amount DECIMAL (5,2)
 );

SELECT * FROM TRANSACTION;

DESCRIBE TRANSACTION;

INSERT INTO TRANSACTION (AMOUNT)
VALUES(1.13);

ALTER TABLE TRANSACTION 
AUTO_INCREMENT = 100;

DELETE FROM TRANSACTION
WHERE transaction_id BETWEEN 0 AND 3;

